#!/bin/sh
set -euo pipefail

build() {
	default_build
}

readonly builddir kernel_srcdir kernel_ver LOG_LEVEL

cd "$builddir"

. AKMBUILD

default_build() {
	touch "$builddir"/Makefile
	make ${MAKEFLAGS:-} -C "$kernel_srcdir" M="$builddir" modules
}

if [ $LOG_LEVEL = warn ]; then
	build > "$builddir"/make.log 2>&1
else
	build 2>&1 | tee "$builddir"/make.log
fi
